apiVersion: v1
kind: Service
metadata:
  name: cats-vs-dogs-service
spec:
  selector:
    app: cats-vs-dogs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
